version: "3.7"
services:
  obstetric-fhir: # Changed from hapi-fhir to obstetric-fhir to match BASE_URL
    image: "hapiproject/hapi:latest"
    container_name: obstetric-fhir
    ports:
      - "8083:8080"
    environment:
      SPRING_CONFIG_LOCATION: file:///config/application.yaml
    volumes:
      - ./config:/config
    depends_on:
      - obstetric-db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/fhir/metadata"]
      interval: 30s
      timeout: 10s
      retries: 5

  obstetric-db: # Changed from postgres-db to obstetric-db
    image: postgres:13
    container_name: obstetric-db
    environment:
      POSTGRES_DB: hapi
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5435:5432"
    volumes:
      - obstetric-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  data-generator:
    build: ./data-generator
    container_name: obstetric-data-generator
    depends_on:
      - obstetric-fhir

volumes:
  obstetric-data:
    name: obstetric-data

networks:
  default:
    name: obstetric-network
