FROM hapiproject/hapi:latest

# Set environment variables
ENV SPRING_CONFIG_LOCATION=file:///config/application.yaml
ENV JAVA_OPTS="-Djava.class.path=/app/extra-libs/*"
ENV CLASSPATH="/app/extra-libs/*"