services:
  interceptors:
    build:
      context: ./interceptors
      dockerfile: Dockerfile
    volumes:
      - ./interceptors/target:/build/target

  maternal-fhir:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: maternal-fhir
    ports:
      - "8081:8080"
    environment:
      JAVA_OPTS: "-Djava.class.path=/app/extra-libs/*"
    volumes:
      - ./config:/config
      - ./interceptors/target:/app/extra-libs:ro
    depends_on:
      - interceptors
      - maternal-db
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/fhir/metadata || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  maternal-db:
    image: postgres:13
    container_name: maternal-db
    environment:
      POSTGRES_DB: hapi
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - maternal-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  data-generator:
    build: ./data-generator
    container_name: maternal-data-generator
    depends_on:
      - maternal-fhir

volumes:
  maternal-data:
    name: maternal-data

networks:
  default:
    name: maternal-network