version: "3.7"
services:
  maternal-fhir: # Changed from hapi-fhir to maternal-fhir to match BASE_URL
    image: "hapiproject/hapi:latest"
    container_name: maternal-fhir
    ports:
      - "8081:8080"
    environment:
      SPRING_CONFIG_LOCATION: file:///config/application.yaml
    volumes:
      - ./config:/config
    depends_on:
      - maternal-db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/fhir/metadata"]
      interval: 30s
      timeout: 10s
      retries: 5

  maternal-db: # Changed from postgres-db to maternal-db
    image: postgres:13
    container_name: maternal-db
    environment:
      POSTGRES_DB: hapi
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - maternal-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  data-generator:
    build: ./data-generator
    container_name: maternal-data-generator
    depends_on:
      - maternal-fhir

volumes:
  maternal-data:
    name: maternal-data

networks:
  default:
    name: maternal-network
