version: "3.7"

services:
  search-service:
    build: .
    container_name: fhir-search-service
    ports:
      - "8000:8000"
    networks:
      - fhir-net
    depends_on:
      - maternal-fhir
      - fetal-fhir
      - obstetric-fhir

networks:
  fhir-net:
    external: true
